const { cmd } = require("../command");
const axios = require("axios");
const translate = require("google-translate-api-x");
const fs = require("fs");

cmd(
  {
    pattern: "movieinfo",
    alias: ["mv", "details"],
    desc: "Get advanced movie details with custom header and footer",
    category: "info",
    filename: __filename,
  },
  async (bot, mek, m, { from, q, reply }) => {
    try {
      if (!q) return reply("🎬 කරුණාකර චිත්‍රපටයේ නම ලබා දෙන්න.");

      await bot.sendMessage(from, { react: { text: "🔍", key: mek.key } });

      // TMDB API Data
      const apiKey = "66395349e59ca85d263920958a0329b3"; 
      const searchRes = await axios.get(`https://api.themoviedb.org/3/search/movie?api_key=${apiKey}&query=${encodeURIComponent(q)}`);

      if (!searchRes.data.results || searchRes.data.results.length === 0) {
        return reply("❌ කිසිදු චිත්‍රපටයක් හමු නොවීය.");
      }

      const movie = searchRes.data.results[0];
      const movieDetail = await axios.get(`https://api.themoviedb.org/3/movie/${movie.id}?api_key=${apiKey}`);
      const data = movieDetail.data;

      // Summary එක සිංහලට පරිවර්තනය කිරීම
      const translation = await translate(data.overview, { to: 'si' });
      const sinhalaSummary = translation.text;

      // --- Custom Header ---
      let detailsMsg = `🅢🅔🅒🅡🅔🅣 🅜🅞🅥🅘🅔 🅒🅛🅤🅑 🅒🅘🅝🅔🅜🅐 🎦\n\n`;
      
      detailsMsg += `📌 *Title:* ${data.title} (${data.release_date.split("-")[0]})\n`;
      detailsMsg += `⭐ *IMDb Rating:* ${data.vote_average.toFixed(1)}/10\n`;
      detailsMsg += `📅 *Release Date:* ${data.release_date}\n`;
      detailsMsg += `⏱️ *Runtime:* ${data.runtime} min\n\n`;
      detailsMsg += `📝 *සාරාංශය (සිංහලෙන්):*\n${sinhalaSummary}\n\n`;

      // --- Custom Footer (.apply එකෙන් එන දේ) ---
      if (fs.existsSync("./caption.txt")) {
        const footerCaption = fs.readFileSync("./caption.txt", "utf8");
        // Footer එකේ {filename} වැනි දේ තිබේ නම් ඒවා ඉවත් කර පිරිසිදු caption එක ගනී
        const cleanFooter = footerCaption.replace(/{filename}/g, "").replace(/{size}/g, "").trim();
        detailsMsg += `---\n${cleanFooter}`;
      } else {
        detailsMsg += `*Generated by Movie Bot*`;
      }

      const posterPath = `https://image.tmdb.org/t/p/w500${data.poster_path}`;

      await bot.sendMessage(
        from,
        {
          image: { url: posterPath },
          caption: detailsMsg,
        },
        { quoted: mek }
      );

      await bot.sendMessage(from, { react: { text: "✅", key: mek.key } });

    } catch (e) {
      console.log("MOVIE ERROR:", e);
      reply("❌ තොරතුරු ලබා ගැනීමේදී දෝෂයක් සිදු විය.");
    }
  }
);
